"""add_raw_scores_and_overtime_flag

Revision ID: ae864b45a7f5
Revises: d4e5f6a7b8c9
Create Date: 2026-06-30 11:45:33.381981
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae864b45a7f5'
down_revision: Union[str, None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attempts', sa.Column('listening_raw', sa.Integer(), nullable=True))
    op.add_column('attempts', sa.Column('reading_raw', sa.Integer(), nullable=True))
    op.add_column('attempts', sa.Column('flagged_overtime', sa.Boolean(), nullable=False, server_default='false'))
    op.create_index(op.f('ix_speaking_sessions_status'), 'speaking_sessions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_speaking_sessions_status'), table_name='speaking_sessions')
    op.drop_column('attempts', 'flagged_overtime')
    op.drop_column('attempts', 'reading_raw')
    op.drop_column('attempts', 'listening_raw')
    # ### end Alembic commands ###
