/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteRouteImport } from './routes/_test/route'
import { Route as StudentRouteRouteImport } from './routes/_student/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSpeakingExaminerRouteImport } from './routes/_authenticated/speaking-examiner'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedTestsIndexRouteImport } from './routes/_authenticated/tests/index'
import { Route as AuthenticatedStudentsIndexRouteImport } from './routes/_authenticated/students/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedResultsIndexRouteImport } from './routes/_authenticated/results/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedDevicesIndexRouteImport } from './routes/_authenticated/devices/index'
import { Route as AuthenticatedAnalyticsIndexRouteImport } from './routes/_authenticated/analytics/index'
import { Route as TestTakeTestTestIdRouteImport } from './routes/_test/take-test.$testId'
import { Route as StudentStudentTestsRouteImport } from './routes/_student/student/tests'
import { Route as StudentStudentProfileRouteImport } from './routes/_student/student/profile'
import { Route as StudentStudentDashboardRouteImport } from './routes/_student/student/dashboard'
import { Route as AuthenticatedTestsImportRouteImport } from './routes/_authenticated/tests/import'
import { Route as AuthenticatedTestsCreateRouteImport } from './routes/_authenticated/tests/create'
import { Route as AuthenticatedTestsTestIdRouteImport } from './routes/_authenticated/tests/$testId'
import { Route as AuthenticatedStudentsStudentIdRouteImport } from './routes/_authenticated/students.$studentId'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedResultsAttemptIdRouteImport } from './routes/_authenticated/results/$attemptId'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as StudentStudentResultsIndexRouteImport } from './routes/_student/student/results/index'
import { Route as AuthenticatedTestsTestIdIndexRouteImport } from './routes/_authenticated/tests/$testId.index'
import { Route as StudentStudentResultsAttemptIdRouteImport } from './routes/_student/student/results/$attemptId'
import { Route as AuthenticatedTestsTestIdEditRouteImport } from './routes/_authenticated/tests/$testId.edit'
import { Route as AuthenticatedResultsStudentsStudentIdRouteImport } from './routes/_authenticated/results/students.$studentId'
import { Route as TestTestsTestIdPreviewRouteRouteImport } from './routes/_test/tests/$testId/preview/route'
import { Route as TestTakeTestBookSlugTestSlugRouteRouteImport } from './routes/_test/take-test/$bookSlug/$testSlug/route'
import { Route as TestPracticeBookSlugTestSlugRouteRouteImport } from './routes/_test/practice/$bookSlug/$testSlug/route'
import { Route as TestTestsTestIdPreviewIndexRouteImport } from './routes/_test/tests/$testId/preview/index'
import { Route as TestTakeTestBookSlugTestSlugIndexRouteImport } from './routes/_test/take-test/$bookSlug/$testSlug/index'
import { Route as TestTakeTestBookSlugTestSlugReviewRouteImport } from './routes/_test/take-test/$bookSlug/$testSlug/review'
import { Route as TestTestsTestIdPreviewSectionRouteRouteImport } from './routes/_test/tests/$testId/preview/$section/route'
import { Route as TestTakeTestBookSlugTestSlugSectionRouteRouteImport } from './routes/_test/take-test/$bookSlug/$testSlug/$section/route'
import { Route as TestPracticeBookSlugTestSlugSectionRouteRouteImport } from './routes/_test/practice/$bookSlug/$testSlug/$section/route'
import { Route as TestTestsTestIdPreviewSectionIndexRouteImport } from './routes/_test/tests/$testId/preview/$section/index'
import { Route as TestTakeTestBookSlugTestSlugSectionIndexRouteImport } from './routes/_test/take-test/$bookSlug/$testSlug/$section/index'
import { Route as TestTestsTestIdPreviewSectionPartRouteImport } from './routes/_test/tests/$testId/preview/$section/$part'
import { Route as TestTakeTestBookSlugTestSlugSectionPartRouteImport } from './routes/_test/take-test/$bookSlug/$testSlug/$section/$part'
import { Route as TestPracticeBookSlugTestSlugSectionPartRouteImport } from './routes/_test/practice/$bookSlug/$testSlug/$section/$part'

const TestRouteRoute = TestRouteRouteImport.update({
  id: '/_test',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRouteRoute = StudentRouteRouteImport.update({
  id: '/_student',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSpeakingExaminerRoute =
  AuthenticatedSpeakingExaminerRouteImport.update({
    id: '/speaking-examiner',
    path: '/speaking-examiner',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTestsIndexRoute = AuthenticatedTestsIndexRouteImport.update({
  id: '/tests/',
  path: '/tests/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudentsIndexRoute =
  AuthenticatedStudentsIndexRouteImport.update({
    id: '/students/',
    path: '/students/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedResultsIndexRoute =
  AuthenticatedResultsIndexRouteImport.update({
    id: '/results/',
    path: '/results/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDevicesIndexRoute =
  AuthenticatedDevicesIndexRouteImport.update({
    id: '/devices/',
    path: '/devices/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalyticsIndexRoute =
  AuthenticatedAnalyticsIndexRouteImport.update({
    id: '/analytics/',
    path: '/analytics/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const TestTakeTestTestIdRoute = TestTakeTestTestIdRouteImport.update({
  id: '/take-test/$testId',
  path: '/take-test/$testId',
  getParentRoute: () => TestRouteRoute,
} as any)
const StudentStudentTestsRoute = StudentStudentTestsRouteImport.update({
  id: '/student/tests',
  path: '/student/tests',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentStudentProfileRoute = StudentStudentProfileRouteImport.update({
  id: '/student/profile',
  path: '/student/profile',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentStudentDashboardRoute = StudentStudentDashboardRouteImport.update({
  id: '/student/dashboard',
  path: '/student/dashboard',
  getParentRoute: () => StudentRouteRoute,
} as any)
const AuthenticatedTestsImportRoute =
  AuthenticatedTestsImportRouteImport.update({
    id: '/tests/import',
    path: '/tests/import',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTestsCreateRoute =
  AuthenticatedTestsCreateRouteImport.update({
    id: '/tests/create',
    path: '/tests/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTestsTestIdRoute =
  AuthenticatedTestsTestIdRouteImport.update({
    id: '/tests/$testId',
    path: '/tests/$testId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentsStudentIdRoute =
  AuthenticatedStudentsStudentIdRouteImport.update({
    id: '/students/$studentId',
    path: '/students/$studentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedResultsAttemptIdRoute =
  AuthenticatedResultsAttemptIdRouteImport.update({
    id: '/results/$attemptId',
    path: '/results/$attemptId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const StudentStudentResultsIndexRoute =
  StudentStudentResultsIndexRouteImport.update({
    id: '/student/results/',
    path: '/student/results/',
    getParentRoute: () => StudentRouteRoute,
  } as any)
const AuthenticatedTestsTestIdIndexRoute =
  AuthenticatedTestsTestIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTestsTestIdRoute,
  } as any)
const StudentStudentResultsAttemptIdRoute =
  StudentStudentResultsAttemptIdRouteImport.update({
    id: '/student/results/$attemptId',
    path: '/student/results/$attemptId',
    getParentRoute: () => StudentRouteRoute,
  } as any)
const AuthenticatedTestsTestIdEditRoute =
  AuthenticatedTestsTestIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedTestsTestIdRoute,
  } as any)
const AuthenticatedResultsStudentsStudentIdRoute =
  AuthenticatedResultsStudentsStudentIdRouteImport.update({
    id: '/results/students/$studentId',
    path: '/results/students/$studentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const TestTestsTestIdPreviewRouteRoute =
  TestTestsTestIdPreviewRouteRouteImport.update({
    id: '/tests/$testId/preview',
    path: '/tests/$testId/preview',
    getParentRoute: () => TestRouteRoute,
  } as any)
const TestTakeTestBookSlugTestSlugRouteRoute =
  TestTakeTestBookSlugTestSlugRouteRouteImport.update({
    id: '/take-test/$bookSlug/$testSlug',
    path: '/take-test/$bookSlug/$testSlug',
    getParentRoute: () => TestRouteRoute,
  } as any)
const TestPracticeBookSlugTestSlugRouteRoute =
  TestPracticeBookSlugTestSlugRouteRouteImport.update({
    id: '/practice/$bookSlug/$testSlug',
    path: '/practice/$bookSlug/$testSlug',
    getParentRoute: () => TestRouteRoute,
  } as any)
const TestTestsTestIdPreviewIndexRoute =
  TestTestsTestIdPreviewIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TestTestsTestIdPreviewRouteRoute,
  } as any)
const TestTakeTestBookSlugTestSlugIndexRoute =
  TestTakeTestBookSlugTestSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TestTakeTestBookSlugTestSlugRouteRoute,
  } as any)
const TestTakeTestBookSlugTestSlugReviewRoute =
  TestTakeTestBookSlugTestSlugReviewRouteImport.update({
    id: '/review',
    path: '/review',
    getParentRoute: () => TestTakeTestBookSlugTestSlugRouteRoute,
  } as any)
const TestTestsTestIdPreviewSectionRouteRoute =
  TestTestsTestIdPreviewSectionRouteRouteImport.update({
    id: '/$section',
    path: '/$section',
    getParentRoute: () => TestTestsTestIdPreviewRouteRoute,
  } as any)
const TestTakeTestBookSlugTestSlugSectionRouteRoute =
  TestTakeTestBookSlugTestSlugSectionRouteRouteImport.update({
    id: '/$section',
    path: '/$section',
    getParentRoute: () => TestTakeTestBookSlugTestSlugRouteRoute,
  } as any)
const TestPracticeBookSlugTestSlugSectionRouteRoute =
  TestPracticeBookSlugTestSlugSectionRouteRouteImport.update({
    id: '/$section',
    path: '/$section',
    getParentRoute: () => TestPracticeBookSlugTestSlugRouteRoute,
  } as any)
const TestTestsTestIdPreviewSectionIndexRoute =
  TestTestsTestIdPreviewSectionIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TestTestsTestIdPreviewSectionRouteRoute,
  } as any)
const TestTakeTestBookSlugTestSlugSectionIndexRoute =
  TestTakeTestBookSlugTestSlugSectionIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TestTakeTestBookSlugTestSlugSectionRouteRoute,
  } as any)
const TestTestsTestIdPreviewSectionPartRoute =
  TestTestsTestIdPreviewSectionPartRouteImport.update({
    id: '/$part',
    path: '/$part',
    getParentRoute: () => TestTestsTestIdPreviewSectionRouteRoute,
  } as any)
const TestTakeTestBookSlugTestSlugSectionPartRoute =
  TestTakeTestBookSlugTestSlugSectionPartRouteImport.update({
    id: '/$part',
    path: '/$part',
    getParentRoute: () => TestTakeTestBookSlugTestSlugSectionRouteRoute,
  } as any)
const TestPracticeBookSlugTestSlugSectionPartRoute =
  TestPracticeBookSlugTestSlugSectionPartRouteImport.update({
    id: '/$part',
    path: '/$part',
    getParentRoute: () => TestPracticeBookSlugTestSlugSectionRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/speaking-examiner': typeof AuthenticatedSpeakingExaminerRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/results/$attemptId': typeof AuthenticatedResultsAttemptIdRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/students/$studentId': typeof AuthenticatedStudentsStudentIdRoute
  '/tests/$testId': typeof AuthenticatedTestsTestIdRouteWithChildren
  '/tests/create': typeof AuthenticatedTestsCreateRoute
  '/tests/import': typeof AuthenticatedTestsImportRoute
  '/student/dashboard': typeof StudentStudentDashboardRoute
  '/student/profile': typeof StudentStudentProfileRoute
  '/student/tests': typeof StudentStudentTestsRoute
  '/take-test/$testId': typeof TestTakeTestTestIdRoute
  '/analytics/': typeof AuthenticatedAnalyticsIndexRoute
  '/devices/': typeof AuthenticatedDevicesIndexRoute
  '/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/results/': typeof AuthenticatedResultsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/students/': typeof AuthenticatedStudentsIndexRoute
  '/tests/': typeof AuthenticatedTestsIndexRoute
  '/practice/$bookSlug/$testSlug': typeof TestPracticeBookSlugTestSlugRouteRouteWithChildren
  '/take-test/$bookSlug/$testSlug': typeof TestTakeTestBookSlugTestSlugRouteRouteWithChildren
  '/tests/$testId/preview': typeof TestTestsTestIdPreviewRouteRouteWithChildren
  '/results/students/$studentId': typeof AuthenticatedResultsStudentsStudentIdRoute
  '/tests/$testId/edit': typeof AuthenticatedTestsTestIdEditRoute
  '/student/results/$attemptId': typeof StudentStudentResultsAttemptIdRoute
  '/tests/$testId/': typeof AuthenticatedTestsTestIdIndexRoute
  '/student/results/': typeof StudentStudentResultsIndexRoute
  '/practice/$bookSlug/$testSlug/$section': typeof TestPracticeBookSlugTestSlugSectionRouteRouteWithChildren
  '/take-test/$bookSlug/$testSlug/$section': typeof TestTakeTestBookSlugTestSlugSectionRouteRouteWithChildren
  '/tests/$testId/preview/$section': typeof TestTestsTestIdPreviewSectionRouteRouteWithChildren
  '/take-test/$bookSlug/$testSlug/review': typeof TestTakeTestBookSlugTestSlugReviewRoute
  '/take-test/$bookSlug/$testSlug/': typeof TestTakeTestBookSlugTestSlugIndexRoute
  '/tests/$testId/preview/': typeof TestTestsTestIdPreviewIndexRoute
  '/practice/$bookSlug/$testSlug/$section/$part': typeof TestPracticeBookSlugTestSlugSectionPartRoute
  '/take-test/$bookSlug/$testSlug/$section/$part': typeof TestTakeTestBookSlugTestSlugSectionPartRoute
  '/tests/$testId/preview/$section/$part': typeof TestTestsTestIdPreviewSectionPartRoute
  '/take-test/$bookSlug/$testSlug/$section/': typeof TestTakeTestBookSlugTestSlugSectionIndexRoute
  '/tests/$testId/preview/$section/': typeof TestTestsTestIdPreviewSectionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof authLoginRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/speaking-examiner': typeof AuthenticatedSpeakingExaminerRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/results/$attemptId': typeof AuthenticatedResultsAttemptIdRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/students/$studentId': typeof AuthenticatedStudentsStudentIdRoute
  '/tests/create': typeof AuthenticatedTestsCreateRoute
  '/tests/import': typeof AuthenticatedTestsImportRoute
  '/student/dashboard': typeof StudentStudentDashboardRoute
  '/student/profile': typeof StudentStudentProfileRoute
  '/student/tests': typeof StudentStudentTestsRoute
  '/take-test/$testId': typeof TestTakeTestTestIdRoute
  '/analytics': typeof AuthenticatedAnalyticsIndexRoute
  '/devices': typeof AuthenticatedDevicesIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/results': typeof AuthenticatedResultsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/students': typeof AuthenticatedStudentsIndexRoute
  '/tests': typeof AuthenticatedTestsIndexRoute
  '/practice/$bookSlug/$testSlug': typeof TestPracticeBookSlugTestSlugRouteRouteWithChildren
  '/results/students/$studentId': typeof AuthenticatedResultsStudentsStudentIdRoute
  '/tests/$testId/edit': typeof AuthenticatedTestsTestIdEditRoute
  '/student/results/$attemptId': typeof StudentStudentResultsAttemptIdRoute
  '/tests/$testId': typeof AuthenticatedTestsTestIdIndexRoute
  '/student/results': typeof StudentStudentResultsIndexRoute
  '/practice/$bookSlug/$testSlug/$section': typeof TestPracticeBookSlugTestSlugSectionRouteRouteWithChildren
  '/take-test/$bookSlug/$testSlug/review': typeof TestTakeTestBookSlugTestSlugReviewRoute
  '/take-test/$bookSlug/$testSlug': typeof TestTakeTestBookSlugTestSlugIndexRoute
  '/tests/$testId/preview': typeof TestTestsTestIdPreviewIndexRoute
  '/practice/$bookSlug/$testSlug/$section/$part': typeof TestPracticeBookSlugTestSlugSectionPartRoute
  '/take-test/$bookSlug/$testSlug/$section/$part': typeof TestTakeTestBookSlugTestSlugSectionPartRoute
  '/tests/$testId/preview/$section/$part': typeof TestTestsTestIdPreviewSectionPartRoute
  '/take-test/$bookSlug/$testSlug/$section': typeof TestTakeTestBookSlugTestSlugSectionIndexRoute
  '/tests/$testId/preview/$section': typeof TestTestsTestIdPreviewSectionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_student': typeof StudentRouteRouteWithChildren
  '/_test': typeof TestRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/speaking-examiner': typeof AuthenticatedSpeakingExaminerRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/results/$attemptId': typeof AuthenticatedResultsAttemptIdRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/students/$studentId': typeof AuthenticatedStudentsStudentIdRoute
  '/_authenticated/tests/$testId': typeof AuthenticatedTestsTestIdRouteWithChildren
  '/_authenticated/tests/create': typeof AuthenticatedTestsCreateRoute
  '/_authenticated/tests/import': typeof AuthenticatedTestsImportRoute
  '/_student/student/dashboard': typeof StudentStudentDashboardRoute
  '/_student/student/profile': typeof StudentStudentProfileRoute
  '/_student/student/tests': typeof StudentStudentTestsRoute
  '/_test/take-test/$testId': typeof TestTakeTestTestIdRoute
  '/_authenticated/analytics/': typeof AuthenticatedAnalyticsIndexRoute
  '/_authenticated/devices/': typeof AuthenticatedDevicesIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/results/': typeof AuthenticatedResultsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/students/': typeof AuthenticatedStudentsIndexRoute
  '/_authenticated/tests/': typeof AuthenticatedTestsIndexRoute
  '/_test/practice/$bookSlug/$testSlug': typeof TestPracticeBookSlugTestSlugRouteRouteWithChildren
  '/_test/take-test/$bookSlug/$testSlug': typeof TestTakeTestBookSlugTestSlugRouteRouteWithChildren
  '/_test/tests/$testId/preview': typeof TestTestsTestIdPreviewRouteRouteWithChildren
  '/_authenticated/results/students/$studentId': typeof AuthenticatedResultsStudentsStudentIdRoute
  '/_authenticated/tests/$testId/edit': typeof AuthenticatedTestsTestIdEditRoute
  '/_student/student/results/$attemptId': typeof StudentStudentResultsAttemptIdRoute
  '/_authenticated/tests/$testId/': typeof AuthenticatedTestsTestIdIndexRoute
  '/_student/student/results/': typeof StudentStudentResultsIndexRoute
  '/_test/practice/$bookSlug/$testSlug/$section': typeof TestPracticeBookSlugTestSlugSectionRouteRouteWithChildren
  '/_test/take-test/$bookSlug/$testSlug/$section': typeof TestTakeTestBookSlugTestSlugSectionRouteRouteWithChildren
  '/_test/tests/$testId/preview/$section': typeof TestTestsTestIdPreviewSectionRouteRouteWithChildren
  '/_test/take-test/$bookSlug/$testSlug/review': typeof TestTakeTestBookSlugTestSlugReviewRoute
  '/_test/take-test/$bookSlug/$testSlug/': typeof TestTakeTestBookSlugTestSlugIndexRoute
  '/_test/tests/$testId/preview/': typeof TestTestsTestIdPreviewIndexRoute
  '/_test/practice/$bookSlug/$testSlug/$section/$part': typeof TestPracticeBookSlugTestSlugSectionPartRoute
  '/_test/take-test/$bookSlug/$testSlug/$section/$part': typeof TestTakeTestBookSlugTestSlugSectionPartRoute
  '/_test/tests/$testId/preview/$section/$part': typeof TestTestsTestIdPreviewSectionPartRoute
  '/_test/take-test/$bookSlug/$testSlug/$section/': typeof TestTakeTestBookSlugTestSlugSectionIndexRoute
  '/_test/tests/$testId/preview/$section/': typeof TestTestsTestIdPreviewSectionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/login'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/speaking-examiner'
    | '/errors/$error'
    | '/results/$attemptId'
    | '/settings/account'
    | '/settings/appearance'
    | '/students/$studentId'
    | '/tests/$testId'
    | '/tests/create'
    | '/tests/import'
    | '/student/dashboard'
    | '/student/profile'
    | '/student/tests'
    | '/take-test/$testId'
    | '/analytics/'
    | '/devices/'
    | '/help-center/'
    | '/results/'
    | '/settings/'
    | '/students/'
    | '/tests/'
    | '/practice/$bookSlug/$testSlug'
    | '/take-test/$bookSlug/$testSlug'
    | '/tests/$testId/preview'
    | '/results/students/$studentId'
    | '/tests/$testId/edit'
    | '/student/results/$attemptId'
    | '/tests/$testId/'
    | '/student/results/'
    | '/practice/$bookSlug/$testSlug/$section'
    | '/take-test/$bookSlug/$testSlug/$section'
    | '/tests/$testId/preview/$section'
    | '/take-test/$bookSlug/$testSlug/review'
    | '/take-test/$bookSlug/$testSlug/'
    | '/tests/$testId/preview/'
    | '/practice/$bookSlug/$testSlug/$section/$part'
    | '/take-test/$bookSlug/$testSlug/$section/$part'
    | '/tests/$testId/preview/$section/$part'
    | '/take-test/$bookSlug/$testSlug/$section/'
    | '/tests/$testId/preview/$section/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/speaking-examiner'
    | '/errors/$error'
    | '/results/$attemptId'
    | '/settings/account'
    | '/settings/appearance'
    | '/students/$studentId'
    | '/tests/create'
    | '/tests/import'
    | '/student/dashboard'
    | '/student/profile'
    | '/student/tests'
    | '/take-test/$testId'
    | '/analytics'
    | '/devices'
    | '/help-center'
    | '/results'
    | '/settings'
    | '/students'
    | '/tests'
    | '/practice/$bookSlug/$testSlug'
    | '/results/students/$studentId'
    | '/tests/$testId/edit'
    | '/student/results/$attemptId'
    | '/tests/$testId'
    | '/student/results'
    | '/practice/$bookSlug/$testSlug/$section'
    | '/take-test/$bookSlug/$testSlug/review'
    | '/take-test/$bookSlug/$testSlug'
    | '/tests/$testId/preview'
    | '/practice/$bookSlug/$testSlug/$section/$part'
    | '/take-test/$bookSlug/$testSlug/$section/$part'
    | '/tests/$testId/preview/$section/$part'
    | '/take-test/$bookSlug/$testSlug/$section'
    | '/tests/$testId/preview/$section'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_student'
    | '/_test'
    | '/_authenticated/settings'
    | '/(auth)/login'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/speaking-examiner'
    | '/_authenticated/'
    | '/_authenticated/errors/$error'
    | '/_authenticated/results/$attemptId'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/students/$studentId'
    | '/_authenticated/tests/$testId'
    | '/_authenticated/tests/create'
    | '/_authenticated/tests/import'
    | '/_student/student/dashboard'
    | '/_student/student/profile'
    | '/_student/student/tests'
    | '/_test/take-test/$testId'
    | '/_authenticated/analytics/'
    | '/_authenticated/devices/'
    | '/_authenticated/help-center/'
    | '/_authenticated/results/'
    | '/_authenticated/settings/'
    | '/_authenticated/students/'
    | '/_authenticated/tests/'
    | '/_test/practice/$bookSlug/$testSlug'
    | '/_test/take-test/$bookSlug/$testSlug'
    | '/_test/tests/$testId/preview'
    | '/_authenticated/results/students/$studentId'
    | '/_authenticated/tests/$testId/edit'
    | '/_student/student/results/$attemptId'
    | '/_authenticated/tests/$testId/'
    | '/_student/student/results/'
    | '/_test/practice/$bookSlug/$testSlug/$section'
    | '/_test/take-test/$bookSlug/$testSlug/$section'
    | '/_test/tests/$testId/preview/$section'
    | '/_test/take-test/$bookSlug/$testSlug/review'
    | '/_test/take-test/$bookSlug/$testSlug/'
    | '/_test/tests/$testId/preview/'
    | '/_test/practice/$bookSlug/$testSlug/$section/$part'
    | '/_test/take-test/$bookSlug/$testSlug/$section/$part'
    | '/_test/tests/$testId/preview/$section/$part'
    | '/_test/take-test/$bookSlug/$testSlug/$section/'
    | '/_test/tests/$testId/preview/$section/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  StudentRouteRoute: typeof StudentRouteRouteWithChildren
  TestRouteRoute: typeof TestRouteRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_test': {
      id: '/_test'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof TestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_student': {
      id: '/_student'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StudentRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/speaking-examiner': {
      id: '/_authenticated/speaking-examiner'
      path: '/speaking-examiner'
      fullPath: '/speaking-examiner'
      preLoaderRoute: typeof AuthenticatedSpeakingExaminerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tests/': {
      id: '/_authenticated/tests/'
      path: '/tests'
      fullPath: '/tests/'
      preLoaderRoute: typeof AuthenticatedTestsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students/': {
      id: '/_authenticated/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof AuthenticatedStudentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/results/': {
      id: '/_authenticated/results/'
      path: '/results'
      fullPath: '/results/'
      preLoaderRoute: typeof AuthenticatedResultsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center/'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/devices/': {
      id: '/_authenticated/devices/'
      path: '/devices'
      fullPath: '/devices/'
      preLoaderRoute: typeof AuthenticatedDevicesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics/': {
      id: '/_authenticated/analytics/'
      path: '/analytics'
      fullPath: '/analytics/'
      preLoaderRoute: typeof AuthenticatedAnalyticsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_test/take-test/$testId': {
      id: '/_test/take-test/$testId'
      path: '/take-test/$testId'
      fullPath: '/take-test/$testId'
      preLoaderRoute: typeof TestTakeTestTestIdRouteImport
      parentRoute: typeof TestRouteRoute
    }
    '/_student/student/tests': {
      id: '/_student/student/tests'
      path: '/student/tests'
      fullPath: '/student/tests'
      preLoaderRoute: typeof StudentStudentTestsRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/_student/student/profile': {
      id: '/_student/student/profile'
      path: '/student/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentStudentProfileRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/_student/student/dashboard': {
      id: '/_student/student/dashboard'
      path: '/student/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentStudentDashboardRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/_authenticated/tests/import': {
      id: '/_authenticated/tests/import'
      path: '/tests/import'
      fullPath: '/tests/import'
      preLoaderRoute: typeof AuthenticatedTestsImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tests/create': {
      id: '/_authenticated/tests/create'
      path: '/tests/create'
      fullPath: '/tests/create'
      preLoaderRoute: typeof AuthenticatedTestsCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tests/$testId': {
      id: '/_authenticated/tests/$testId'
      path: '/tests/$testId'
      fullPath: '/tests/$testId'
      preLoaderRoute: typeof AuthenticatedTestsTestIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students/$studentId': {
      id: '/_authenticated/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof AuthenticatedStudentsStudentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/results/$attemptId': {
      id: '/_authenticated/results/$attemptId'
      path: '/results/$attemptId'
      fullPath: '/results/$attemptId'
      preLoaderRoute: typeof AuthenticatedResultsAttemptIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_student/student/results/': {
      id: '/_student/student/results/'
      path: '/student/results'
      fullPath: '/student/results/'
      preLoaderRoute: typeof StudentStudentResultsIndexRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/_authenticated/tests/$testId/': {
      id: '/_authenticated/tests/$testId/'
      path: '/'
      fullPath: '/tests/$testId/'
      preLoaderRoute: typeof AuthenticatedTestsTestIdIndexRouteImport
      parentRoute: typeof AuthenticatedTestsTestIdRoute
    }
    '/_student/student/results/$attemptId': {
      id: '/_student/student/results/$attemptId'
      path: '/student/results/$attemptId'
      fullPath: '/student/results/$attemptId'
      preLoaderRoute: typeof StudentStudentResultsAttemptIdRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/_authenticated/tests/$testId/edit': {
      id: '/_authenticated/tests/$testId/edit'
      path: '/edit'
      fullPath: '/tests/$testId/edit'
      preLoaderRoute: typeof AuthenticatedTestsTestIdEditRouteImport
      parentRoute: typeof AuthenticatedTestsTestIdRoute
    }
    '/_authenticated/results/students/$studentId': {
      id: '/_authenticated/results/students/$studentId'
      path: '/results/students/$studentId'
      fullPath: '/results/students/$studentId'
      preLoaderRoute: typeof AuthenticatedResultsStudentsStudentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_test/tests/$testId/preview': {
      id: '/_test/tests/$testId/preview'
      path: '/tests/$testId/preview'
      fullPath: '/tests/$testId/preview'
      preLoaderRoute: typeof TestTestsTestIdPreviewRouteRouteImport
      parentRoute: typeof TestRouteRoute
    }
    '/_test/take-test/$bookSlug/$testSlug': {
      id: '/_test/take-test/$bookSlug/$testSlug'
      path: '/take-test/$bookSlug/$testSlug'
      fullPath: '/take-test/$bookSlug/$testSlug'
      preLoaderRoute: typeof TestTakeTestBookSlugTestSlugRouteRouteImport
      parentRoute: typeof TestRouteRoute
    }
    '/_test/practice/$bookSlug/$testSlug': {
      id: '/_test/practice/$bookSlug/$testSlug'
      path: '/practice/$bookSlug/$testSlug'
      fullPath: '/practice/$bookSlug/$testSlug'
      preLoaderRoute: typeof TestPracticeBookSlugTestSlugRouteRouteImport
      parentRoute: typeof TestRouteRoute
    }
    '/_test/tests/$testId/preview/': {
      id: '/_test/tests/$testId/preview/'
      path: '/'
      fullPath: '/tests/$testId/preview/'
      preLoaderRoute: typeof TestTestsTestIdPreviewIndexRouteImport
      parentRoute: typeof TestTestsTestIdPreviewRouteRoute
    }
    '/_test/take-test/$bookSlug/$testSlug/': {
      id: '/_test/take-test/$bookSlug/$testSlug/'
      path: '/'
      fullPath: '/take-test/$bookSlug/$testSlug/'
      preLoaderRoute: typeof TestTakeTestBookSlugTestSlugIndexRouteImport
      parentRoute: typeof TestTakeTestBookSlugTestSlugRouteRoute
    }
    '/_test/take-test/$bookSlug/$testSlug/review': {
      id: '/_test/take-test/$bookSlug/$testSlug/review'
      path: '/review'
      fullPath: '/take-test/$bookSlug/$testSlug/review'
      preLoaderRoute: typeof TestTakeTestBookSlugTestSlugReviewRouteImport
      parentRoute: typeof TestTakeTestBookSlugTestSlugRouteRoute
    }
    '/_test/tests/$testId/preview/$section': {
      id: '/_test/tests/$testId/preview/$section'
      path: '/$section'
      fullPath: '/tests/$testId/preview/$section'
      preLoaderRoute: typeof TestTestsTestIdPreviewSectionRouteRouteImport
      parentRoute: typeof TestTestsTestIdPreviewRouteRoute
    }
    '/_test/take-test/$bookSlug/$testSlug/$section': {
      id: '/_test/take-test/$bookSlug/$testSlug/$section'
      path: '/$section'
      fullPath: '/take-test/$bookSlug/$testSlug/$section'
      preLoaderRoute: typeof TestTakeTestBookSlugTestSlugSectionRouteRouteImport
      parentRoute: typeof TestTakeTestBookSlugTestSlugRouteRoute
    }
    '/_test/practice/$bookSlug/$testSlug/$section': {
      id: '/_test/practice/$bookSlug/$testSlug/$section'
      path: '/$section'
      fullPath: '/practice/$bookSlug/$testSlug/$section'
      preLoaderRoute: typeof TestPracticeBookSlugTestSlugSectionRouteRouteImport
      parentRoute: typeof TestPracticeBookSlugTestSlugRouteRoute
    }
    '/_test/tests/$testId/preview/$section/': {
      id: '/_test/tests/$testId/preview/$section/'
      path: '/'
      fullPath: '/tests/$testId/preview/$section/'
      preLoaderRoute: typeof TestTestsTestIdPreviewSectionIndexRouteImport
      parentRoute: typeof TestTestsTestIdPreviewSectionRouteRoute
    }
    '/_test/take-test/$bookSlug/$testSlug/$section/': {
      id: '/_test/take-test/$bookSlug/$testSlug/$section/'
      path: '/'
      fullPath: '/take-test/$bookSlug/$testSlug/$section/'
      preLoaderRoute: typeof TestTakeTestBookSlugTestSlugSectionIndexRouteImport
      parentRoute: typeof TestTakeTestBookSlugTestSlugSectionRouteRoute
    }
    '/_test/tests/$testId/preview/$section/$part': {
      id: '/_test/tests/$testId/preview/$section/$part'
      path: '/$part'
      fullPath: '/tests/$testId/preview/$section/$part'
      preLoaderRoute: typeof TestTestsTestIdPreviewSectionPartRouteImport
      parentRoute: typeof TestTestsTestIdPreviewSectionRouteRoute
    }
    '/_test/take-test/$bookSlug/$testSlug/$section/$part': {
      id: '/_test/take-test/$bookSlug/$testSlug/$section/$part'
      path: '/$part'
      fullPath: '/take-test/$bookSlug/$testSlug/$section/$part'
      preLoaderRoute: typeof TestTakeTestBookSlugTestSlugSectionPartRouteImport
      parentRoute: typeof TestTakeTestBookSlugTestSlugSectionRouteRoute
    }
    '/_test/practice/$bookSlug/$testSlug/$section/$part': {
      id: '/_test/practice/$bookSlug/$testSlug/$section/$part'
      path: '/$part'
      fullPath: '/practice/$bookSlug/$testSlug/$section/$part'
      preLoaderRoute: typeof TestPracticeBookSlugTestSlugSectionPartRouteImport
      parentRoute: typeof TestPracticeBookSlugTestSlugSectionRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedTestsTestIdRouteChildren {
  AuthenticatedTestsTestIdEditRoute: typeof AuthenticatedTestsTestIdEditRoute
  AuthenticatedTestsTestIdIndexRoute: typeof AuthenticatedTestsTestIdIndexRoute
}

const AuthenticatedTestsTestIdRouteChildren: AuthenticatedTestsTestIdRouteChildren =
  {
    AuthenticatedTestsTestIdEditRoute: AuthenticatedTestsTestIdEditRoute,
    AuthenticatedTestsTestIdIndexRoute: AuthenticatedTestsTestIdIndexRoute,
  }

const AuthenticatedTestsTestIdRouteWithChildren =
  AuthenticatedTestsTestIdRoute._addFileChildren(
    AuthenticatedTestsTestIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedSpeakingExaminerRoute: typeof AuthenticatedSpeakingExaminerRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedResultsAttemptIdRoute: typeof AuthenticatedResultsAttemptIdRoute
  AuthenticatedStudentsStudentIdRoute: typeof AuthenticatedStudentsStudentIdRoute
  AuthenticatedTestsTestIdRoute: typeof AuthenticatedTestsTestIdRouteWithChildren
  AuthenticatedTestsCreateRoute: typeof AuthenticatedTestsCreateRoute
  AuthenticatedTestsImportRoute: typeof AuthenticatedTestsImportRoute
  AuthenticatedAnalyticsIndexRoute: typeof AuthenticatedAnalyticsIndexRoute
  AuthenticatedDevicesIndexRoute: typeof AuthenticatedDevicesIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedResultsIndexRoute: typeof AuthenticatedResultsIndexRoute
  AuthenticatedStudentsIndexRoute: typeof AuthenticatedStudentsIndexRoute
  AuthenticatedTestsIndexRoute: typeof AuthenticatedTestsIndexRoute
  AuthenticatedResultsStudentsStudentIdRoute: typeof AuthenticatedResultsStudentsStudentIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedSpeakingExaminerRoute: AuthenticatedSpeakingExaminerRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedResultsAttemptIdRoute: AuthenticatedResultsAttemptIdRoute,
  AuthenticatedStudentsStudentIdRoute: AuthenticatedStudentsStudentIdRoute,
  AuthenticatedTestsTestIdRoute: AuthenticatedTestsTestIdRouteWithChildren,
  AuthenticatedTestsCreateRoute: AuthenticatedTestsCreateRoute,
  AuthenticatedTestsImportRoute: AuthenticatedTestsImportRoute,
  AuthenticatedAnalyticsIndexRoute: AuthenticatedAnalyticsIndexRoute,
  AuthenticatedDevicesIndexRoute: AuthenticatedDevicesIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedResultsIndexRoute: AuthenticatedResultsIndexRoute,
  AuthenticatedStudentsIndexRoute: AuthenticatedStudentsIndexRoute,
  AuthenticatedTestsIndexRoute: AuthenticatedTestsIndexRoute,
  AuthenticatedResultsStudentsStudentIdRoute:
    AuthenticatedResultsStudentsStudentIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface StudentRouteRouteChildren {
  StudentStudentDashboardRoute: typeof StudentStudentDashboardRoute
  StudentStudentProfileRoute: typeof StudentStudentProfileRoute
  StudentStudentTestsRoute: typeof StudentStudentTestsRoute
  StudentStudentResultsAttemptIdRoute: typeof StudentStudentResultsAttemptIdRoute
  StudentStudentResultsIndexRoute: typeof StudentStudentResultsIndexRoute
}

const StudentRouteRouteChildren: StudentRouteRouteChildren = {
  StudentStudentDashboardRoute: StudentStudentDashboardRoute,
  StudentStudentProfileRoute: StudentStudentProfileRoute,
  StudentStudentTestsRoute: StudentStudentTestsRoute,
  StudentStudentResultsAttemptIdRoute: StudentStudentResultsAttemptIdRoute,
  StudentStudentResultsIndexRoute: StudentStudentResultsIndexRoute,
}

const StudentRouteRouteWithChildren = StudentRouteRoute._addFileChildren(
  StudentRouteRouteChildren,
)

interface TestPracticeBookSlugTestSlugSectionRouteRouteChildren {
  TestPracticeBookSlugTestSlugSectionPartRoute: typeof TestPracticeBookSlugTestSlugSectionPartRoute
}

const TestPracticeBookSlugTestSlugSectionRouteRouteChildren: TestPracticeBookSlugTestSlugSectionRouteRouteChildren =
  {
    TestPracticeBookSlugTestSlugSectionPartRoute:
      TestPracticeBookSlugTestSlugSectionPartRoute,
  }

const TestPracticeBookSlugTestSlugSectionRouteRouteWithChildren =
  TestPracticeBookSlugTestSlugSectionRouteRoute._addFileChildren(
    TestPracticeBookSlugTestSlugSectionRouteRouteChildren,
  )

interface TestPracticeBookSlugTestSlugRouteRouteChildren {
  TestPracticeBookSlugTestSlugSectionRouteRoute: typeof TestPracticeBookSlugTestSlugSectionRouteRouteWithChildren
}

const TestPracticeBookSlugTestSlugRouteRouteChildren: TestPracticeBookSlugTestSlugRouteRouteChildren =
  {
    TestPracticeBookSlugTestSlugSectionRouteRoute:
      TestPracticeBookSlugTestSlugSectionRouteRouteWithChildren,
  }

const TestPracticeBookSlugTestSlugRouteRouteWithChildren =
  TestPracticeBookSlugTestSlugRouteRoute._addFileChildren(
    TestPracticeBookSlugTestSlugRouteRouteChildren,
  )

interface TestTakeTestBookSlugTestSlugSectionRouteRouteChildren {
  TestTakeTestBookSlugTestSlugSectionPartRoute: typeof TestTakeTestBookSlugTestSlugSectionPartRoute
  TestTakeTestBookSlugTestSlugSectionIndexRoute: typeof TestTakeTestBookSlugTestSlugSectionIndexRoute
}

const TestTakeTestBookSlugTestSlugSectionRouteRouteChildren: TestTakeTestBookSlugTestSlugSectionRouteRouteChildren =
  {
    TestTakeTestBookSlugTestSlugSectionPartRoute:
      TestTakeTestBookSlugTestSlugSectionPartRoute,
    TestTakeTestBookSlugTestSlugSectionIndexRoute:
      TestTakeTestBookSlugTestSlugSectionIndexRoute,
  }

const TestTakeTestBookSlugTestSlugSectionRouteRouteWithChildren =
  TestTakeTestBookSlugTestSlugSectionRouteRoute._addFileChildren(
    TestTakeTestBookSlugTestSlugSectionRouteRouteChildren,
  )

interface TestTakeTestBookSlugTestSlugRouteRouteChildren {
  TestTakeTestBookSlugTestSlugSectionRouteRoute: typeof TestTakeTestBookSlugTestSlugSectionRouteRouteWithChildren
  TestTakeTestBookSlugTestSlugReviewRoute: typeof TestTakeTestBookSlugTestSlugReviewRoute
  TestTakeTestBookSlugTestSlugIndexRoute: typeof TestTakeTestBookSlugTestSlugIndexRoute
}

const TestTakeTestBookSlugTestSlugRouteRouteChildren: TestTakeTestBookSlugTestSlugRouteRouteChildren =
  {
    TestTakeTestBookSlugTestSlugSectionRouteRoute:
      TestTakeTestBookSlugTestSlugSectionRouteRouteWithChildren,
    TestTakeTestBookSlugTestSlugReviewRoute:
      TestTakeTestBookSlugTestSlugReviewRoute,
    TestTakeTestBookSlugTestSlugIndexRoute:
      TestTakeTestBookSlugTestSlugIndexRoute,
  }

const TestTakeTestBookSlugTestSlugRouteRouteWithChildren =
  TestTakeTestBookSlugTestSlugRouteRoute._addFileChildren(
    TestTakeTestBookSlugTestSlugRouteRouteChildren,
  )

interface TestTestsTestIdPreviewSectionRouteRouteChildren {
  TestTestsTestIdPreviewSectionPartRoute: typeof TestTestsTestIdPreviewSectionPartRoute
  TestTestsTestIdPreviewSectionIndexRoute: typeof TestTestsTestIdPreviewSectionIndexRoute
}

const TestTestsTestIdPreviewSectionRouteRouteChildren: TestTestsTestIdPreviewSectionRouteRouteChildren =
  {
    TestTestsTestIdPreviewSectionPartRoute:
      TestTestsTestIdPreviewSectionPartRoute,
    TestTestsTestIdPreviewSectionIndexRoute:
      TestTestsTestIdPreviewSectionIndexRoute,
  }

const TestTestsTestIdPreviewSectionRouteRouteWithChildren =
  TestTestsTestIdPreviewSectionRouteRoute._addFileChildren(
    TestTestsTestIdPreviewSectionRouteRouteChildren,
  )

interface TestTestsTestIdPreviewRouteRouteChildren {
  TestTestsTestIdPreviewSectionRouteRoute: typeof TestTestsTestIdPreviewSectionRouteRouteWithChildren
  TestTestsTestIdPreviewIndexRoute: typeof TestTestsTestIdPreviewIndexRoute
}

const TestTestsTestIdPreviewRouteRouteChildren: TestTestsTestIdPreviewRouteRouteChildren =
  {
    TestTestsTestIdPreviewSectionRouteRoute:
      TestTestsTestIdPreviewSectionRouteRouteWithChildren,
    TestTestsTestIdPreviewIndexRoute: TestTestsTestIdPreviewIndexRoute,
  }

const TestTestsTestIdPreviewRouteRouteWithChildren =
  TestTestsTestIdPreviewRouteRoute._addFileChildren(
    TestTestsTestIdPreviewRouteRouteChildren,
  )

interface TestRouteRouteChildren {
  TestTakeTestTestIdRoute: typeof TestTakeTestTestIdRoute
  TestPracticeBookSlugTestSlugRouteRoute: typeof TestPracticeBookSlugTestSlugRouteRouteWithChildren
  TestTakeTestBookSlugTestSlugRouteRoute: typeof TestTakeTestBookSlugTestSlugRouteRouteWithChildren
  TestTestsTestIdPreviewRouteRoute: typeof TestTestsTestIdPreviewRouteRouteWithChildren
}

const TestRouteRouteChildren: TestRouteRouteChildren = {
  TestTakeTestTestIdRoute: TestTakeTestTestIdRoute,
  TestPracticeBookSlugTestSlugRouteRoute:
    TestPracticeBookSlugTestSlugRouteRouteWithChildren,
  TestTakeTestBookSlugTestSlugRouteRoute:
    TestTakeTestBookSlugTestSlugRouteRouteWithChildren,
  TestTestsTestIdPreviewRouteRoute:
    TestTestsTestIdPreviewRouteRouteWithChildren,
}

const TestRouteRouteWithChildren = TestRouteRoute._addFileChildren(
  TestRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  StudentRouteRoute: StudentRouteRouteWithChildren,
  TestRouteRoute: TestRouteRouteWithChildren,
  authLoginRoute: authLoginRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
