/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClerkRouteRouteImport } from './routes/clerk/route'
import { Route as TestRouteRouteImport } from './routes/_test/route'
import { Route as StudentRouteRouteImport } from './routes/_student/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSpeakingExaminerRouteImport } from './routes/_authenticated/speaking-examiner'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as ClerkAuthenticatedRouteRouteImport } from './routes/clerk/_authenticated/route'
import { Route as ClerkauthRouteRouteImport } from './routes/clerk/(auth)/route'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedTestsIndexRouteImport } from './routes/_authenticated/tests/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedStudentsIndexRouteImport } from './routes/_authenticated/students/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedResultsIndexRouteImport } from './routes/_authenticated/results/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as ClerkAuthenticatedUserManagementRouteImport } from './routes/clerk/_authenticated/user-management'
import { Route as ClerkauthSignUpRouteImport } from './routes/clerk/(auth)/sign-up'
import { Route as ClerkauthSignInRouteImport } from './routes/clerk/(auth)/sign-in'
import { Route as TestTakeTestTestIdRouteImport } from './routes/_test/take-test.$testId'
import { Route as StudentStudentTestsRouteImport } from './routes/_student/student/tests'
import { Route as StudentStudentResultsRouteImport } from './routes/_student/student/results'
import { Route as StudentStudentDashboardRouteImport } from './routes/_student/student/dashboard'
import { Route as AuthenticatedTestsImportRouteImport } from './routes/_authenticated/tests/import'
import { Route as AuthenticatedTestsCreateRouteImport } from './routes/_authenticated/tests/create'
import { Route as AuthenticatedTestsTestIdRouteImport } from './routes/_authenticated/tests/$testId'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedResultsAttemptIdRouteImport } from './routes/_authenticated/results/$attemptId'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedTestsTestIdIndexRouteImport } from './routes/_authenticated/tests/$testId.index'
import { Route as StudentStudentResultsAttemptIdRouteImport } from './routes/_student/student/results.$attemptId'
import { Route as AuthenticatedTestsTestIdEditRouteImport } from './routes/_authenticated/tests/$testId.edit'
import { Route as TestTakeTestBookSlugTestSlugRouteRouteImport } from './routes/_test/take-test/$bookSlug/$testSlug/route'
import { Route as TestTakeTestBookSlugTestSlugIndexRouteImport } from './routes/_test/take-test/$bookSlug/$testSlug/index'
import { Route as TestTakeTestBookSlugTestSlugSectionRouteImport } from './routes/_test/take-test/$bookSlug/$testSlug/$section'

const ClerkRouteRoute = ClerkRouteRouteImport.update({
  id: '/clerk',
  path: '/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRouteRoute = TestRouteRouteImport.update({
  id: '/_test',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRouteRoute = StudentRouteRouteImport.update({
  id: '/_student',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSpeakingExaminerRoute =
  AuthenticatedSpeakingExaminerRouteImport.update({
    id: '/speaking-examiner',
    path: '/speaking-examiner',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkAuthenticatedRouteRoute = ClerkAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const ClerkauthRouteRoute = ClerkauthRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTestsIndexRoute = AuthenticatedTestsIndexRouteImport.update({
  id: '/tests/',
  path: '/tests/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudentsIndexRoute =
  AuthenticatedStudentsIndexRouteImport.update({
    id: '/students/',
    path: '/students/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedResultsIndexRoute =
  AuthenticatedResultsIndexRouteImport.update({
    id: '/results/',
    path: '/results/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ClerkAuthenticatedUserManagementRoute =
  ClerkAuthenticatedUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => ClerkAuthenticatedRouteRoute,
  } as any)
const ClerkauthSignUpRoute = ClerkauthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const ClerkauthSignInRoute = ClerkauthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const TestTakeTestTestIdRoute = TestTakeTestTestIdRouteImport.update({
  id: '/take-test/$testId',
  path: '/take-test/$testId',
  getParentRoute: () => TestRouteRoute,
} as any)
const StudentStudentTestsRoute = StudentStudentTestsRouteImport.update({
  id: '/student/tests',
  path: '/student/tests',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentStudentResultsRoute = StudentStudentResultsRouteImport.update({
  id: '/student/results',
  path: '/student/results',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentStudentDashboardRoute = StudentStudentDashboardRouteImport.update({
  id: '/student/dashboard',
  path: '/student/dashboard',
  getParentRoute: () => StudentRouteRoute,
} as any)
const AuthenticatedTestsImportRoute =
  AuthenticatedTestsImportRouteImport.update({
    id: '/tests/import',
    path: '/tests/import',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTestsCreateRoute =
  AuthenticatedTestsCreateRouteImport.update({
    id: '/tests/create',
    path: '/tests/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTestsTestIdRoute =
  AuthenticatedTestsTestIdRouteImport.update({
    id: '/tests/$testId',
    path: '/tests/$testId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedResultsAttemptIdRoute =
  AuthenticatedResultsAttemptIdRouteImport.update({
    id: '/results/$attemptId',
    path: '/results/$attemptId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTestsTestIdIndexRoute =
  AuthenticatedTestsTestIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTestsTestIdRoute,
  } as any)
const StudentStudentResultsAttemptIdRoute =
  StudentStudentResultsAttemptIdRouteImport.update({
    id: '/$attemptId',
    path: '/$attemptId',
    getParentRoute: () => StudentStudentResultsRoute,
  } as any)
const AuthenticatedTestsTestIdEditRoute =
  AuthenticatedTestsTestIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedTestsTestIdRoute,
  } as any)
const TestTakeTestBookSlugTestSlugRouteRoute =
  TestTakeTestBookSlugTestSlugRouteRouteImport.update({
    id: '/take-test/$bookSlug/$testSlug',
    path: '/take-test/$bookSlug/$testSlug',
    getParentRoute: () => TestRouteRoute,
  } as any)
const TestTakeTestBookSlugTestSlugIndexRoute =
  TestTakeTestBookSlugTestSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TestTakeTestBookSlugTestSlugRouteRoute,
  } as any)
const TestTakeTestBookSlugTestSlugSectionRoute =
  TestTakeTestBookSlugTestSlugSectionRouteImport.update({
    id: '/$section',
    path: '/$section',
    getParentRoute: () => TestTakeTestBookSlugTestSlugRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/clerk': typeof ClerkauthRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/otp': typeof authOtpRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/speaking-examiner': typeof AuthenticatedSpeakingExaminerRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/results/$attemptId': typeof AuthenticatedResultsAttemptIdRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/tests/$testId': typeof AuthenticatedTestsTestIdRouteWithChildren
  '/tests/create': typeof AuthenticatedTestsCreateRoute
  '/tests/import': typeof AuthenticatedTestsImportRoute
  '/student/dashboard': typeof StudentStudentDashboardRoute
  '/student/results': typeof StudentStudentResultsRouteWithChildren
  '/student/tests': typeof StudentStudentTestsRoute
  '/take-test/$testId': typeof TestTakeTestTestIdRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/apps/': typeof AuthenticatedAppsIndexRoute
  '/chats/': typeof AuthenticatedChatsIndexRoute
  '/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/results/': typeof AuthenticatedResultsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/students/': typeof AuthenticatedStudentsIndexRoute
  '/tasks/': typeof AuthenticatedTasksIndexRoute
  '/tests/': typeof AuthenticatedTestsIndexRoute
  '/take-test/$bookSlug/$testSlug': typeof TestTakeTestBookSlugTestSlugRouteRouteWithChildren
  '/tests/$testId/edit': typeof AuthenticatedTestsTestIdEditRoute
  '/student/results/$attemptId': typeof StudentStudentResultsAttemptIdRoute
  '/tests/$testId/': typeof AuthenticatedTestsTestIdIndexRoute
  '/take-test/$bookSlug/$testSlug/$section': typeof TestTakeTestBookSlugTestSlugSectionRoute
  '/take-test/$bookSlug/$testSlug/': typeof TestTakeTestBookSlugTestSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/clerk': typeof ClerkauthRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/otp': typeof authOtpRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/speaking-examiner': typeof AuthenticatedSpeakingExaminerRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/results/$attemptId': typeof AuthenticatedResultsAttemptIdRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/tests/create': typeof AuthenticatedTestsCreateRoute
  '/tests/import': typeof AuthenticatedTestsImportRoute
  '/student/dashboard': typeof StudentStudentDashboardRoute
  '/student/results': typeof StudentStudentResultsRouteWithChildren
  '/student/tests': typeof StudentStudentTestsRoute
  '/take-test/$testId': typeof TestTakeTestTestIdRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/results': typeof AuthenticatedResultsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/students': typeof AuthenticatedStudentsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/tests': typeof AuthenticatedTestsIndexRoute
  '/tests/$testId/edit': typeof AuthenticatedTestsTestIdEditRoute
  '/student/results/$attemptId': typeof StudentStudentResultsAttemptIdRoute
  '/tests/$testId': typeof AuthenticatedTestsTestIdIndexRoute
  '/take-test/$bookSlug/$testSlug/$section': typeof TestTakeTestBookSlugTestSlugSectionRoute
  '/take-test/$bookSlug/$testSlug': typeof TestTakeTestBookSlugTestSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_student': typeof StudentRouteRouteWithChildren
  '/_test': typeof TestRouteRouteWithChildren
  '/clerk': typeof ClerkRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/clerk/(auth)': typeof ClerkauthRouteRouteWithChildren
  '/clerk/_authenticated': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/speaking-examiner': typeof AuthenticatedSpeakingExaminerRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/results/$attemptId': typeof AuthenticatedResultsAttemptIdRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/tests/$testId': typeof AuthenticatedTestsTestIdRouteWithChildren
  '/_authenticated/tests/create': typeof AuthenticatedTestsCreateRoute
  '/_authenticated/tests/import': typeof AuthenticatedTestsImportRoute
  '/_student/student/dashboard': typeof StudentStudentDashboardRoute
  '/_student/student/results': typeof StudentStudentResultsRouteWithChildren
  '/_student/student/tests': typeof StudentStudentTestsRoute
  '/_test/take-test/$testId': typeof TestTakeTestTestIdRoute
  '/clerk/(auth)/sign-in': typeof ClerkauthSignInRoute
  '/clerk/(auth)/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/_authenticated/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/results/': typeof AuthenticatedResultsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/students/': typeof AuthenticatedStudentsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/tests/': typeof AuthenticatedTestsIndexRoute
  '/_test/take-test/$bookSlug/$testSlug': typeof TestTakeTestBookSlugTestSlugRouteRouteWithChildren
  '/_authenticated/tests/$testId/edit': typeof AuthenticatedTestsTestIdEditRoute
  '/_student/student/results/$attemptId': typeof StudentStudentResultsAttemptIdRoute
  '/_authenticated/tests/$testId/': typeof AuthenticatedTestsTestIdIndexRoute
  '/_test/take-test/$bookSlug/$testSlug/$section': typeof TestTakeTestBookSlugTestSlugSectionRoute
  '/_test/take-test/$bookSlug/$testSlug/': typeof TestTakeTestBookSlugTestSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clerk'
    | '/settings'
    | '/forgot-password'
    | '/login'
    | '/otp'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/speaking-examiner'
    | '/errors/$error'
    | '/results/$attemptId'
    | '/settings/account'
    | '/settings/appearance'
    | '/tests/$testId'
    | '/tests/create'
    | '/tests/import'
    | '/student/dashboard'
    | '/student/results'
    | '/student/tests'
    | '/take-test/$testId'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/apps/'
    | '/chats/'
    | '/help-center/'
    | '/results/'
    | '/settings/'
    | '/students/'
    | '/tasks/'
    | '/tests/'
    | '/take-test/$bookSlug/$testSlug'
    | '/tests/$testId/edit'
    | '/student/results/$attemptId'
    | '/tests/$testId/'
    | '/take-test/$bookSlug/$testSlug/$section'
    | '/take-test/$bookSlug/$testSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clerk'
    | '/forgot-password'
    | '/login'
    | '/otp'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/speaking-examiner'
    | '/errors/$error'
    | '/results/$attemptId'
    | '/settings/account'
    | '/settings/appearance'
    | '/tests/create'
    | '/tests/import'
    | '/student/dashboard'
    | '/student/results'
    | '/student/tests'
    | '/take-test/$testId'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/apps'
    | '/chats'
    | '/help-center'
    | '/results'
    | '/settings'
    | '/students'
    | '/tasks'
    | '/tests'
    | '/tests/$testId/edit'
    | '/student/results/$attemptId'
    | '/tests/$testId'
    | '/take-test/$bookSlug/$testSlug/$section'
    | '/take-test/$bookSlug/$testSlug'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_student'
    | '/_test'
    | '/clerk'
    | '/_authenticated/settings'
    | '/clerk/(auth)'
    | '/clerk/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/otp'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/speaking-examiner'
    | '/_authenticated/'
    | '/_authenticated/errors/$error'
    | '/_authenticated/results/$attemptId'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/tests/$testId'
    | '/_authenticated/tests/create'
    | '/_authenticated/tests/import'
    | '/_student/student/dashboard'
    | '/_student/student/results'
    | '/_student/student/tests'
    | '/_test/take-test/$testId'
    | '/clerk/(auth)/sign-in'
    | '/clerk/(auth)/sign-up'
    | '/clerk/_authenticated/user-management'
    | '/_authenticated/apps/'
    | '/_authenticated/chats/'
    | '/_authenticated/help-center/'
    | '/_authenticated/results/'
    | '/_authenticated/settings/'
    | '/_authenticated/students/'
    | '/_authenticated/tasks/'
    | '/_authenticated/tests/'
    | '/_test/take-test/$bookSlug/$testSlug'
    | '/_authenticated/tests/$testId/edit'
    | '/_student/student/results/$attemptId'
    | '/_authenticated/tests/$testId/'
    | '/_test/take-test/$bookSlug/$testSlug/$section'
    | '/_test/take-test/$bookSlug/$testSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  StudentRouteRoute: typeof StudentRouteRouteWithChildren
  TestRouteRoute: typeof TestRouteRouteWithChildren
  ClerkRouteRoute: typeof ClerkRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authOtpRoute: typeof authOtpRoute
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/clerk': {
      id: '/clerk'
      path: '/clerk'
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_test': {
      id: '/_test'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof TestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_student': {
      id: '/_student'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StudentRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/speaking-examiner': {
      id: '/_authenticated/speaking-examiner'
      path: '/speaking-examiner'
      fullPath: '/speaking-examiner'
      preLoaderRoute: typeof AuthenticatedSpeakingExaminerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk/_authenticated': {
      id: '/clerk/_authenticated'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkAuthenticatedRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/clerk/(auth)': {
      id: '/clerk/(auth)'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkauthRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tests/': {
      id: '/_authenticated/tests/'
      path: '/tests'
      fullPath: '/tests/'
      preLoaderRoute: typeof AuthenticatedTestsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students/': {
      id: '/_authenticated/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof AuthenticatedStudentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/results/': {
      id: '/_authenticated/results/'
      path: '/results'
      fullPath: '/results/'
      preLoaderRoute: typeof AuthenticatedResultsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center/'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats/'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/clerk/_authenticated/user-management': {
      id: '/clerk/_authenticated/user-management'
      path: '/user-management'
      fullPath: '/clerk/user-management'
      preLoaderRoute: typeof ClerkAuthenticatedUserManagementRouteImport
      parentRoute: typeof ClerkAuthenticatedRouteRoute
    }
    '/clerk/(auth)/sign-up': {
      id: '/clerk/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/clerk/sign-up'
      preLoaderRoute: typeof ClerkauthSignUpRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/clerk/(auth)/sign-in': {
      id: '/clerk/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/clerk/sign-in'
      preLoaderRoute: typeof ClerkauthSignInRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/_test/take-test/$testId': {
      id: '/_test/take-test/$testId'
      path: '/take-test/$testId'
      fullPath: '/take-test/$testId'
      preLoaderRoute: typeof TestTakeTestTestIdRouteImport
      parentRoute: typeof TestRouteRoute
    }
    '/_student/student/tests': {
      id: '/_student/student/tests'
      path: '/student/tests'
      fullPath: '/student/tests'
      preLoaderRoute: typeof StudentStudentTestsRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/_student/student/results': {
      id: '/_student/student/results'
      path: '/student/results'
      fullPath: '/student/results'
      preLoaderRoute: typeof StudentStudentResultsRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/_student/student/dashboard': {
      id: '/_student/student/dashboard'
      path: '/student/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentStudentDashboardRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/_authenticated/tests/import': {
      id: '/_authenticated/tests/import'
      path: '/tests/import'
      fullPath: '/tests/import'
      preLoaderRoute: typeof AuthenticatedTestsImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tests/create': {
      id: '/_authenticated/tests/create'
      path: '/tests/create'
      fullPath: '/tests/create'
      preLoaderRoute: typeof AuthenticatedTestsCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tests/$testId': {
      id: '/_authenticated/tests/$testId'
      path: '/tests/$testId'
      fullPath: '/tests/$testId'
      preLoaderRoute: typeof AuthenticatedTestsTestIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/results/$attemptId': {
      id: '/_authenticated/results/$attemptId'
      path: '/results/$attemptId'
      fullPath: '/results/$attemptId'
      preLoaderRoute: typeof AuthenticatedResultsAttemptIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tests/$testId/': {
      id: '/_authenticated/tests/$testId/'
      path: '/'
      fullPath: '/tests/$testId/'
      preLoaderRoute: typeof AuthenticatedTestsTestIdIndexRouteImport
      parentRoute: typeof AuthenticatedTestsTestIdRoute
    }
    '/_student/student/results/$attemptId': {
      id: '/_student/student/results/$attemptId'
      path: '/$attemptId'
      fullPath: '/student/results/$attemptId'
      preLoaderRoute: typeof StudentStudentResultsAttemptIdRouteImport
      parentRoute: typeof StudentStudentResultsRoute
    }
    '/_authenticated/tests/$testId/edit': {
      id: '/_authenticated/tests/$testId/edit'
      path: '/edit'
      fullPath: '/tests/$testId/edit'
      preLoaderRoute: typeof AuthenticatedTestsTestIdEditRouteImport
      parentRoute: typeof AuthenticatedTestsTestIdRoute
    }
    '/_test/take-test/$bookSlug/$testSlug': {
      id: '/_test/take-test/$bookSlug/$testSlug'
      path: '/take-test/$bookSlug/$testSlug'
      fullPath: '/take-test/$bookSlug/$testSlug'
      preLoaderRoute: typeof TestTakeTestBookSlugTestSlugRouteRouteImport
      parentRoute: typeof TestRouteRoute
    }
    '/_test/take-test/$bookSlug/$testSlug/': {
      id: '/_test/take-test/$bookSlug/$testSlug/'
      path: '/'
      fullPath: '/take-test/$bookSlug/$testSlug/'
      preLoaderRoute: typeof TestTakeTestBookSlugTestSlugIndexRouteImport
      parentRoute: typeof TestTakeTestBookSlugTestSlugRouteRoute
    }
    '/_test/take-test/$bookSlug/$testSlug/$section': {
      id: '/_test/take-test/$bookSlug/$testSlug/$section'
      path: '/$section'
      fullPath: '/take-test/$bookSlug/$testSlug/$section'
      preLoaderRoute: typeof TestTakeTestBookSlugTestSlugSectionRouteImport
      parentRoute: typeof TestTakeTestBookSlugTestSlugRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedTestsTestIdRouteChildren {
  AuthenticatedTestsTestIdEditRoute: typeof AuthenticatedTestsTestIdEditRoute
  AuthenticatedTestsTestIdIndexRoute: typeof AuthenticatedTestsTestIdIndexRoute
}

const AuthenticatedTestsTestIdRouteChildren: AuthenticatedTestsTestIdRouteChildren =
  {
    AuthenticatedTestsTestIdEditRoute: AuthenticatedTestsTestIdEditRoute,
    AuthenticatedTestsTestIdIndexRoute: AuthenticatedTestsTestIdIndexRoute,
  }

const AuthenticatedTestsTestIdRouteWithChildren =
  AuthenticatedTestsTestIdRoute._addFileChildren(
    AuthenticatedTestsTestIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedSpeakingExaminerRoute: typeof AuthenticatedSpeakingExaminerRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedResultsAttemptIdRoute: typeof AuthenticatedResultsAttemptIdRoute
  AuthenticatedTestsTestIdRoute: typeof AuthenticatedTestsTestIdRouteWithChildren
  AuthenticatedTestsCreateRoute: typeof AuthenticatedTestsCreateRoute
  AuthenticatedTestsImportRoute: typeof AuthenticatedTestsImportRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedResultsIndexRoute: typeof AuthenticatedResultsIndexRoute
  AuthenticatedStudentsIndexRoute: typeof AuthenticatedStudentsIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedTestsIndexRoute: typeof AuthenticatedTestsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedSpeakingExaminerRoute: AuthenticatedSpeakingExaminerRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedResultsAttemptIdRoute: AuthenticatedResultsAttemptIdRoute,
  AuthenticatedTestsTestIdRoute: AuthenticatedTestsTestIdRouteWithChildren,
  AuthenticatedTestsCreateRoute: AuthenticatedTestsCreateRoute,
  AuthenticatedTestsImportRoute: AuthenticatedTestsImportRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedResultsIndexRoute: AuthenticatedResultsIndexRoute,
  AuthenticatedStudentsIndexRoute: AuthenticatedStudentsIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedTestsIndexRoute: AuthenticatedTestsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface StudentStudentResultsRouteChildren {
  StudentStudentResultsAttemptIdRoute: typeof StudentStudentResultsAttemptIdRoute
}

const StudentStudentResultsRouteChildren: StudentStudentResultsRouteChildren = {
  StudentStudentResultsAttemptIdRoute: StudentStudentResultsAttemptIdRoute,
}

const StudentStudentResultsRouteWithChildren =
  StudentStudentResultsRoute._addFileChildren(
    StudentStudentResultsRouteChildren,
  )

interface StudentRouteRouteChildren {
  StudentStudentDashboardRoute: typeof StudentStudentDashboardRoute
  StudentStudentResultsRoute: typeof StudentStudentResultsRouteWithChildren
  StudentStudentTestsRoute: typeof StudentStudentTestsRoute
}

const StudentRouteRouteChildren: StudentRouteRouteChildren = {
  StudentStudentDashboardRoute: StudentStudentDashboardRoute,
  StudentStudentResultsRoute: StudentStudentResultsRouteWithChildren,
  StudentStudentTestsRoute: StudentStudentTestsRoute,
}

const StudentRouteRouteWithChildren = StudentRouteRoute._addFileChildren(
  StudentRouteRouteChildren,
)

interface TestTakeTestBookSlugTestSlugRouteRouteChildren {
  TestTakeTestBookSlugTestSlugSectionRoute: typeof TestTakeTestBookSlugTestSlugSectionRoute
  TestTakeTestBookSlugTestSlugIndexRoute: typeof TestTakeTestBookSlugTestSlugIndexRoute
}

const TestTakeTestBookSlugTestSlugRouteRouteChildren: TestTakeTestBookSlugTestSlugRouteRouteChildren =
  {
    TestTakeTestBookSlugTestSlugSectionRoute:
      TestTakeTestBookSlugTestSlugSectionRoute,
    TestTakeTestBookSlugTestSlugIndexRoute:
      TestTakeTestBookSlugTestSlugIndexRoute,
  }

const TestTakeTestBookSlugTestSlugRouteRouteWithChildren =
  TestTakeTestBookSlugTestSlugRouteRoute._addFileChildren(
    TestTakeTestBookSlugTestSlugRouteRouteChildren,
  )

interface TestRouteRouteChildren {
  TestTakeTestTestIdRoute: typeof TestTakeTestTestIdRoute
  TestTakeTestBookSlugTestSlugRouteRoute: typeof TestTakeTestBookSlugTestSlugRouteRouteWithChildren
}

const TestRouteRouteChildren: TestRouteRouteChildren = {
  TestTakeTestTestIdRoute: TestTakeTestTestIdRoute,
  TestTakeTestBookSlugTestSlugRouteRoute:
    TestTakeTestBookSlugTestSlugRouteRouteWithChildren,
}

const TestRouteRouteWithChildren = TestRouteRoute._addFileChildren(
  TestRouteRouteChildren,
)

interface ClerkauthRouteRouteChildren {
  ClerkauthSignInRoute: typeof ClerkauthSignInRoute
  ClerkauthSignUpRoute: typeof ClerkauthSignUpRoute
}

const ClerkauthRouteRouteChildren: ClerkauthRouteRouteChildren = {
  ClerkauthSignInRoute: ClerkauthSignInRoute,
  ClerkauthSignUpRoute: ClerkauthSignUpRoute,
}

const ClerkauthRouteRouteWithChildren = ClerkauthRouteRoute._addFileChildren(
  ClerkauthRouteRouteChildren,
)

interface ClerkAuthenticatedRouteRouteChildren {
  ClerkAuthenticatedUserManagementRoute: typeof ClerkAuthenticatedUserManagementRoute
}

const ClerkAuthenticatedRouteRouteChildren: ClerkAuthenticatedRouteRouteChildren =
  {
    ClerkAuthenticatedUserManagementRoute:
      ClerkAuthenticatedUserManagementRoute,
  }

const ClerkAuthenticatedRouteRouteWithChildren =
  ClerkAuthenticatedRouteRoute._addFileChildren(
    ClerkAuthenticatedRouteRouteChildren,
  )

interface ClerkRouteRouteChildren {
  ClerkauthRouteRoute: typeof ClerkauthRouteRouteWithChildren
  ClerkAuthenticatedRouteRoute: typeof ClerkAuthenticatedRouteRouteWithChildren
}

const ClerkRouteRouteChildren: ClerkRouteRouteChildren = {
  ClerkauthRouteRoute: ClerkauthRouteRouteWithChildren,
  ClerkAuthenticatedRouteRoute: ClerkAuthenticatedRouteRouteWithChildren,
}

const ClerkRouteRouteWithChildren = ClerkRouteRoute._addFileChildren(
  ClerkRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  StudentRouteRoute: StudentRouteRouteWithChildren,
  TestRouteRoute: TestRouteRouteWithChildren,
  ClerkRouteRoute: ClerkRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authOtpRoute: authOtpRoute,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
